/******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic.c
 *
 * Description: source file for the Ultrasonic driver
 *
 * Author: Youssef ElSayyad
 *
 *******************************************************************************/
#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h> /* For the delay functions */
#include <avr/io.h> /* To use the SREG register */

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
/* Global variable to count the edges on the ECHO PIN*/
static uint8 g_echoEdge = 0;
/* Global variable to hold the value of the time of the high pulse*/
static uint16 g_pulseTime = 0;


/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description : Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init(void) {
	/*ICU_Configurtions with clock=F cpu/8 and RAISING EDGE Detection*/
	ICU_ConfigType ICU_Configurations = { F_CPU_8, RAISING };
	ICU_init(&ICU_Configurations);
	SREG |= (1 << 7);
	/* Set the Call back function pointer in the ICU driver */
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	/*Setting up the Trigger PIN as OUTPUT */
	GPIO_setupPinDirection(TRIGGER_PORTID, TRIGGER_PINID, PIN_OUTPUT);
}

/*
 * Description : Send the Trigger pulse to the ultrasonic
 */

void Ultrasonic_Trigger(void) {
	GPIO_writePin(TRIGGER_PORTID, TRIGGER_PINID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(TRIGGER_PORTID, TRIGGER_PINID, LOGIC_LOW);
}
/*
 * Description : Send the trigger pulse by using Ultrasonic_Trigger function..
 * Start the measurements by the ICU from this moment
 * Return The measured distance in Centimeter
 */
uint16 Ultrasonic_readDistance(void) {
	uint16 Distance;
	/* Send the Trigger pulse to the ultrasonic  */
	Ultrasonic_Trigger();
	/*Calculating the distance*/
	Distance = ( (float) 17000* g_pulseTime) / 1000000;
	return Distance;
}
/*
 * Description : This is the call back function called by the ICU driver
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void) {
	g_echoEdge++;
	if (g_echoEdge == 1) {
		/*
		 * Clear the timer counter register to start from the first detected rising edge
		 */
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	} else if (g_echoEdge == 2) {
		/* Store the ECHO ON time value */
		g_pulseTime = ICU_getInputCaptureValue();
		/* Detect Raising edge */
		ICU_setEdgeDetectionType(RAISING);
		g_echoEdge = 0;
	}
}
